version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    allowed_updates:
      - match:
          dependency_name: "cluster_tools"
      - match:
          dependency_name: "wkw"
    default_reviewers:
      - "philippotto"